routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


Route::get('/registro', 'AuthPersonalizedController@register');
Route::post('/registro_usuario', 'AuthPersonalizedController@register_user')->name('register_user');
Route::post('/registro_persona', 'AuthPersonalizedController@registro_persona');
Route::post('/registro_tienda', 'AuthPersonalizedController@registro_tienda');

Route::get('busqueda/ciudad/search/{ciudad}', 'TiendasController@busquedaCiudad');

Auth::routes(['register' => false]);


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home_index');

Route::get('/perfil', 'PersonasController@perfil')->name('perfil');
Route::get('/cambio_plan', 'PlanesController@cambio_plan')->name('cambio_plan');


Route::post('/perfil/update', 'PersonasController@perfilUpdate')->name('perfil.update');




Route::resource('/role', 'RoleController')->names('role');
Route::resource('/reportes', 'ReportesController')->names('reportes');

/* Modulo de la tienda*/
Route::get('/tiendas/listado', 'TiendasController@tiendas')->name('tiendas.listado');
Route::get('/tiendas/keyup/{variable}', 'TiendasController@keyuptienda');
Route::get('/tiendas/pedidos', 'TiendasController@historial_pedidos')->name('tiendas.historial');

Route::post('/tiendas/pedidos/estado', 'TiendasController@pedido_cambio_estado')->name('tiendas.estado');
Route::get('/tiendas/verpedido/local/{codigo}', 'TiendasController@ver_pedido_local')->name('tiendas.verPedidoLocal');
Route::get('/tiendas/verpedido/domicilio/{codigo}', 'TiendasController@ver_pedido_domi')->name('tiendas.verPedidoDomicilio');
Route::get('/tiendas/cerrar/pedido', 'TiendasController@ver_pedido_domi')->name('tiendas.pedidoDestroy');




Route::resource('/tiendas', 'TiendasController')->names('tiendas');
Route::resource('/zonas', 'ZonasController')->names('zonas');



/* Modulo de productos*/
Route::resource('/productos', 'ProductosController')->names('productos');
Route::get('/productos/keyup/{variable}', 'ProductosController@keyupproducto');


/* Modulo categorias de los productos*/
Route::get('/categoriasproductos/keyup/{variable}', 'CategoriasproductosController@keyup');
Route::resource('/categoriasproductos', 'CategoriasproductosController')->names('categoriasproductos');


/* Adicionales de los productos */
Route::get('adicionales/listar', 'AdicionalesController@index')->name('adicionales.index');
Route::get('adicionales/crear', 'AdicionalesController@crear')->name('adicionales.crear');
Route::PUT('adicionales/store', 'AdicionalesController@store')->name('adicionales.store');
Route::get('adicionales/show/{id}', 'AdicionalesController@show')->name('adicionales.show');
Route::get('adicionales/edicion/{id}', 'AdicionalesController@edicion')->name('adicionales.edicion');
Route::POST('adicionales/update/{id}', 'AdicionalesController@update')->name('adicionales.update');
Route::DELETE('adicionales/delete/{id}', 'AdicionalesController@delete')->name('adicionales.destroy');


/* Modulo de personas */
Route::resource('/personas', 'PersonasController')->names('personas');

Route::get('/perfil/{codigo}', 'PersonasController@perfil')->name('perfil.show');


/* Modulo de seugerencias */

Route::get('/sugerencias', 'FormulariosController@indexsugerencias')->name('sugerencias.index');
Route::get('/sugerencias/edit/{codigo]', 'FormulariosController@showSugerencia')->name('sugerencias.showsugerencia');
Route::DELETE('/sugerencias/delete/{codigo}', 'FormulariosController@deletesugerencias')->name('sugerencias.destroy');

Route::get('/contacto', 'FormulariosController@indexContacto')->name('contacto.index');


/* Modulo de notificaciones */

Route::get('/notification/get', 'HomeController@notification');
Route::get('/notification/show/{id?}', 'HomeController@ver_notification');


/* Modulo de planes */
Route::resource('/planes', 'PlanesController')->names('planes');
Route::get('/planes_asignar', 'PlanesController@asignar')->name('planes.asignar');
Route::post('/asignar_store', 'PlanesController@asignar_store')->name('planes.asignar_store');
Route::get('/asignaciones', 'PlanesController@asignaciones')->name('planes.asignaciones');

 	// ---  actualizar plan
	Route::post('/metodoUpdate', 'PlanesController@metodoPagoActualizacion')->name('planes.metodoUpdate');
	Route::post('/metodoUpdatePay/{valor}', 'PlanesController@metodoUpdatePay')->name('planes.metodoUpdatePay');
  Route::post('/metodoUpdatePayNequi/{valor}', 'PlanesController@metodoUpdatePayNequi')->name('planes.metodoUpdatePayNequi');

  //Ir al pago para actualizar plan
  Route::post('/pagoActualizacionPlan/{pago?}', 'PlanesController@pagoActualizacionPlan')->name('planes.pagoActualizacionPlan');

  /* Verificacion Pago con Nequi */
  Route::get('/wompi/verification/nequi/{id}', 'PlanesController@verification_nequi');
  Route::post('/wompi/verification/pagar/{id}', 'PlanesController@pagar_nequi');
  Route::get('/wompi/verification/transaction/{id}', 'PlanesController@verification_transaction');
  Route::post('/wompi/verification/registro_bd/{id}', 'PlanesController@registro_bd');
  Route::get('/cambio_plan', 'PlanesController@cambio_plan')->name('planes.cambio_plan');

  /*verificacion Pago con Nequi pero tarjetas de credito*/
  Route::get('/wompi/verification/nequi/tarjetas/{id}', 'PlanesController@verification_nequi');



/* Modulo de cupones */
Route::resource('/cupones', 'CuponesController')->names('cupones');


/* Modulo de Epayco */
Route::resource('/epayco', 'EpaycoController')->names('epayco');	
/* Modulo de Epayco */


/* Cerrar sesion*/
Route::get('/logout', 'HomeController@logout');

Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/Http/Controllers/CategoriasproductosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Auth;
use Gate;
use DateTime;


class CategoriasproductosController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        Gate::authorize('haveaccess','categoryProductos.show');


        $usuario = DB::table('role_user')
                        ->select('users.*', 'roles.*', 'role_user.*')
                        ->join('roles', 'role_user.role_id', '=', 'roles.id')
                        ->join('users', 'role_user.user_id', '=', 'users.id')
                        ->where('users.id', Auth::user()->id)->get();

        foreach ($usuario as $user) {
            if ($user->slug == "admin") {
                $categorias = DB::table('categorias_productos')->paginate(10);
                
                return view('categorias_productos.administrator.index', compact('categorias'));
            } else {

                $array_categoria = [];
                $codigo_temporal = [];

                $tiendas = DB::table('detalle_usuario_tiendas')
                                ->select('personas.id', 'detalle_usuario_tiendas.*', 'tiendas.*', 'users.*')
                                ->join('personas', 'detalle_usuario_tiendas.id_persona', '=', 'personas.id')
                                ->join('users', 'personas.user_register', '=', 'users.id')
                                ->join('tiendas', 'detalle_usuario_tiendas.id_tienda', '=', 'tiendas.id_tienda')
                                ->where('users.id', Auth::user()->id)->get();

                foreach ($tiendas as $tienda) {
                    $codigo_tienda = $tienda->id_tienda;
                }

                
                $productos_tienda = DB::table('detalle_tienda_productos')
                        ->select('productos.*', 'detalle_tienda_productos.*')
                        ->join('productos', 'detalle_tienda_productos.id_producto', '=', 'productos.id')
                        ->where('id_tienda', $codigo_tienda)
                        ->get();

                $categorias = DB::table('categorias_productos')->get();


                foreach ($productos_tienda as $producto) {
                    $array_categoria[] = $producto->id_categoria;
                }


                $categorias_temporales = DB::table('categorias_temporales')->where('id_tienda', $codigo_tienda)->get();
                
                foreach ($categorias_temporales as $categoria_temporal) {
                    $codigo_temporal[] = $categoria_temporal->id_categoria;
                }


                /* VER DIFERENCIAS ENTRE FECHAS SEGUN PLAN */

            $detalles_del_plan = DB::table('detalle_planes_tiendas')
              ->select('detalle_planes_tiendas.*', 'tiendas.*', 'tabla_planes.*')
              ->join('tiendas', 'detalle_planes_tiendas.id_detalle_plan_tienda', '=','tiendas.id_tienda')
              ->join('tabla_planes', 'detalle_planes_tiendas.id_detalle_plan', '=','tabla_planes.id_plan')
              ->where([['id_detalle_plan_tienda', $tiendas[0]->id_tienda], ['estado_detalle_plan', '1']])
              ->get();

            $dia_actual = new DateTime(date('Y-m-d'));
            $fecha_proximo_pago = new DateTime($detalles_del_plan[0]->fecha_proximo_pago);

            $funcion = $dia_actual->diff($fecha_proximo_pago);

            if($fecha_proximo_pago < $dia_actual){
              $dias_faltantes = 0;
            }else{
              $dias_faltantes = $funcion->days;
            }

          /* VER DIFERENCIAS ENTRE FECHAS SEGUN PLAN */

          if($dias_faltantes <= 0){
            $planes = DB::table('tabla_planes')->get();
            return view('planes.tienda.pago-plan', compact('planes'));
          }else{
            return view('categorias_productos.index', compact('array_categoria', 'categorias', 'codigo_temporal'));
          }

          
            }
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        
        Gate::authorize('haveaccess','categoryProductos.create');


        $usuario = DB::table('role_user')
          ->select('users.*', 'roles.*', 'role_user.*')
          ->join('roles', 'role_user.role_id', '=', 'roles.id')
          ->join('users', 'role_user.user_id', '=', 'users.id')
          ->where('users.id', Auth::user()->id)->get();


        foreach ($usuario as $user) {
          if ($user->slug == "admin") {

            $dias_faltantes = 1; 

            $tiendas = DB::table('detalle_usuario_tiendas')
                                ->select('personas.id', 'detalle_usuario_tiendas.*', 'tiendas.*', 'users.*')
                                ->join('personas', 'detalle_usuario_tiendas.id_persona', '=', 'personas.id')
                                ->join('users', 'personas.user_register', '=', 'users.id')
                                ->join('tiendas', 'detalle_usuario_tiendas.id_tienda', '=', 'tiendas.id_tienda')
                                ->where('users.id', Auth::user()->id)->get();

          }else{
            $tiendas = DB::table('detalle_usuario_tiendas')
                                ->select('personas.id', 'detalle_usuario_tiendas.*', 'tiendas.*', 'users.*')
                                ->join('personas', 'detalle_usuario_tiendas.id_persona', '=', 'personas.id')
                                ->join('users', 'personas.user_register', '=', 'users.id')
                                ->join('tiendas', 'detalle_usuario_tiendas.id_tienda', '=', 'tiendas.id_tienda')
                                ->where('users.id', Auth::user()->id)->get();
              /* VER DIFERENCIAS ENTRE FECHAS SEGUN PLAN */

              $detalles_del_plan = DB::table('detalle_planes_tiendas')
                ->select('detalle_planes_tiendas.*', 'tiendas.*', 'tabla_planes.*')
                ->join('tiendas', 'detalle_planes_tiendas.id_detalle_plan_tienda', '=','tiendas.id_tienda')
                ->join('tabla_planes', 'detalle_planes_tiendas.id_detalle_plan', '=','tabla_planes.id_plan')
                ->where([['id_detalle_plan_tienda', $tiendas[0]->id_tienda], ['estado_detalle_plan', '1']])
                ->get();

              $dia_actual = new DateTime(date('Y-m-d'));
              $fecha_proximo_pago = new DateTime($detalles_del_plan[0]->fecha_proximo_pago);

              $funcion = $dia_actual->diff($fecha_proximo_pago);

              if($fecha_proximo_pago < $dia_actual){
                $dias_faltantes = 0;
              }else{
                $dias_faltantes = $funcion->days;
              }

            /* VER DIFERENCIAS ENTRE FECHAS SEGUN PLAN */
          }
        }

          if($dias_faltantes <= 0){
            $planes = DB::table('tabla_planes')->get();
            return view('planes.tienda.pago-plan', compact('planes'));
          }else{

            /* VALIDAMOS CUANDO SEA PLAN FREE PARA QUE NO AGREGUE MAS DE 10 PRODUCTOS */

                $total_productos = DB::table('detalle_tienda_productos')
                        ->select('productos.*', 'detalle_tienda_productos.*')
                        ->join('productos', 'detalle_tienda_productos.id_producto', '=', 'productos.id')
                        ->where('id_tienda', $tiendas[0]->id_tienda)
                        ->count();

                $captura_rol = DB::table('role_user')->where('user_id', Auth::user()->id)->get();

                if($captura_rol[0]->role_id == '755'){
                  if($total_productos <= 10){
                     return view('categorias_productos.create');  
                  }else{
                     return view('productos.mensaje_actualizar_plan');
                  }
                }else{
                   return view('categorias_productos.create');
                }

                

                /* FIN VALIDACIONES CUANDO SEA PLAN FREE PARA QUE NO AGREGUE MAS DE 10 PRODUCTOS */
          }

          
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        Gate::authorize('haveaccess','categoryProductos.create');

        $array_categoria = [];

        $request->validate([
            'imagen_categoria' => 'required|mimes:jpg,jpeg,bmp,png',
            'nombre_categoria' => 'required',
        ]);

        //obtenemos el campo file definido en el formulario
        $file = $request->file('imagen_categoria');
        //obtenemos el nombre del archivo
        $imagen_categoria = $file->getClientOriginalName();
        //obtenemos el nombre del archivo
        $imagen_categoria = $file->getClientOriginalName('imagen_categoria');
        \Storage::disk('public')->put($imagen_categoria, \File::get($file));

        

        $tiendas = DB::table('detalle_usuario_tiendas')
                        ->select('personas.id', 'detalle_usuario_tiendas.*', 'tiendas.*', 'users.*')
                        ->join('personas', 'detalle_usuario_tiendas.id_persona', '=', 'personas.id')
                        ->join('users', 'personas.user_register', '=', 'users.id')
                        ->join('tiendas', 'detalle_usuario_tiendas.id_tienda', '=', 'tiendas.id_tienda')
                        ->where('users.id', Auth::user()->id)->get();

        foreach ($tiendas as $tienda) {
            $codigo_tienda = $tienda->id_tienda;
        }

        DB::table('categorias_productos')->insert([
            'imagen_categoria' => $imagen_categoria,
            'nombre_categoria' => $request->nombre_categoria,
            'descripcion_categoria' => $request->descripcion_categoria,
            'estado_categoria' => '3'
        ]);

        $categorias = DB::table('categorias_productos')->orderby('id', 'DESC')->take(1)->get();

resources/views/categorias_productos/administrator/index.blade.php
<!-- Listado de las tiendas, no influye si es Administrador o Cliente -->

@extends('layouts.app')

@section('content')


<div class="data-tables">
    <div class="main-content">
        <div class="container-fluid content-top-gap">
            <div class="data-tables">
                <div class="row">
                    <div class="col-lg-12 chart-grid mb-4">
                        <div class="card card_border p-4">
                            <div class="card-header chart-grid__header pl-0 pt-0">
                                Categorias de todos los productos
                            </div>
                        </div>
                        @include('custom.message')
                    </div>
                    
                    <div class="col-lg-12 chart-grid mb-4">
                        <div class="card card_border p-4">
                            <div class="messaging">
                                <b>Búsqueda de las categorias:</b>
                                <input type="text" name="buscadorProductos" id="buscadorCategoriasProductos" class="form-control" placeholder="Busca tu categoria..." />
                            </div>
                            <br>
                            <table class="table table-bordered table-hover" id="table_categorias_productos">
                                <thead>
                                    <tr>
                                        <th>Imagen Categorias</th>
                                        <th>Nombre Categoria</th>
                                        <th>Descripcion Categoria</th>
                                        <th>Estado</th>
                                        <th colspan="3"><center>Acciones</center></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($categorias as $categoria)

                                        <tr>
                                            <td><img src="{{ asset('/storage/'.$categoria->imagen_categoria) }}" width="150px"/></td>
                                            <td>{{ $categoria->nombre_categoria }}</td>
                                            <td>{{ $categoria->descripcion_categoria }}</td>
                                            @if($categoria->estado_categoria == 1)
                                             <td class="alert alert-info"> Activo </td>
                                            @else
                                             <td class="alert alert-danger">Inactivo</td>
                                            @endif
                                            
                                            @if(Gate::authorize('haveaccess','categoryProductos.edit'))
                                            <td>
                                                <a data-href="{{ route('categoriasproductos.edit', $categoria->id)}}" class="identificador-categoria-producto-update">
                                                    <button type="button" class="btn btn-info btn-sm">
                                                        <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                        </svg>
                                                    </button>
                                                </a>
                                            </td>
                                            @endif

                                            @if(Gate::authorize('haveaccess','categoryProductos.show'))
                                            <td>
                                                <a data-href="{{ route('categoriasproductos.show', $categoria->id)}}" class="identificador-categoria-producto-ver">
                                                    <button type="button" class="btn btn-success btn-sm">
                                                        <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                                            <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                                        </svg>
                                                    </button>
                                                </a>
                                            </td>
                                            @endif

                                            @if(Gate::authorize('haveaccess','categoryProductos.destroy'))
                                            <td>
                                                <form method="POST" action="{{ route('categoriasproductos.destroy', $categoria->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                        <path fill-rule="evenodd" d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/>
                                                    </svg>
                                                </button>
                                                 </form>
                                            </td>
                                            @endif
                                        </tr>
                                        
                                    @endforeach
                                </tbody>
                            </table>
                            <br><br>
                            {{ $categorias->links() }}
                        </div>
                    </div>
                    
                </div>
            </div>      
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-lg" id="modales-tiendas" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" id="modal-body">
        
    </div>
  </div>
</div>

@endsection

resources/views/categorias_productos/administrator/keyup.blade.php
<thead>
                            <tr>
                                <th>Imagen Categorias</th>
                                <th>Nombre Categoria</th>
                                <th>Descripcion Categoria</th>
                                <th>Estado</th>
                                <th colspan="3"><center>Acciones</center></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categorias as $categoria)
                                <tr>
                                    <td><img src="{{ asset('/storage/'.$categoria->imagen_categoria) }}" width="150px"/></td>
                                    <td>{{ $categoria->nombre_categoria }}</td>
                                    <td>{{ $categoria->descripcion_categoria }}</td>
                                    @if($categoria->estado_categoria == 1)
                                     <td class="alert alert-info"> Activo </td>
                                    @else
                                     <td class="alert alert-danger">Inactivo</td>
                                    @endif
                                    @if(Gate::authorize('haveaccess','categoryProductos.edit'))
                                   <td>
                                                <a data-href="{{ route('categoriasproductos.edit', $categoria->id)}}" class="identificador-categoria-producto-update">
                                            <button type="button" class="btn btn-info btn-sm">
                                                <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                </svg>
                                            </button>
                                        </a>
                                    </td>
                                    @endif

                                    @if(Gate::authorize('haveaccess','categoryProductos.show'))
                                     <td>
                                     <a data-href="{{ route('categoriasproductos.show', $categoria->id)}}" class="identificador-categoria-producto-ver">
                                            <button type="button" class="btn btn-success btn-sm">
                                                <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                                </svg>
                                            </button>
                                        </a>
                                    </td>
                                    @endif

                                    @if(Gate::authorize('haveaccess','categoryProductos.destroy'))
                                           <td>
                                                <form method="POST" action="{{ route('categoriasproductos.destroy', $categoria->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                        <path fill-rule="evenodd" d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/>
                                                    </svg>
                                                </button>
                                                 </form>
                                            </td>
                                            @endif
                                </tr>
                            @endforeach
                        </tbody>