routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


Route::get('/registro', 'AuthPersonalizedController@register');
Route::post('/registro_usuario', 'AuthPersonalizedController@register_user')->name('register_user');
Route::post('/registro_persona', 'AuthPersonalizedController@registro_persona');
Route::post('/registro_tienda', 'AuthPersonalizedController@registro_tienda');

Route::get('busqueda/ciudad/search/{ciudad}', 'TiendasController@busquedaCiudad');

Auth::routes(['register' => false]);


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home_index');

Route::get('/perfil', 'PersonasController@perfil')->name('perfil');
Route::get('/cambio_plan', 'PlanesController@cambio_plan')->name('cambio_plan');


Route::post('/perfil/update', 'PersonasController@perfilUpdate')->name('perfil.update');




Route::resource('/role', 'RoleController')->names('role');
Route::resource('/reportes', 'ReportesController')->names('reportes');

/* Modulo de la tienda*/
Route::get('/tiendas/listado', 'TiendasController@tiendas')->name('tiendas.listado');
Route::get('/tiendas/keyup/{variable}', 'TiendasController@keyuptienda');
Route::get('/tiendas/pedidos', 'TiendasController@historial_pedidos')->name('tiendas.historial');

Route::post('/tiendas/pedidos/estado', 'TiendasController@pedido_cambio_estado')->name('tiendas.estado');
Route::get('/tiendas/verpedido/local/{codigo}', 'TiendasController@ver_pedido_local')->name('tiendas.verPedidoLocal');
Route::get('/tiendas/verpedido/domicilio/{codigo}', 'TiendasController@ver_pedido_domi')->name('tiendas.verPedidoDomicilio');
Route::get('/tiendas/cerrar/pedido', 'TiendasController@ver_pedido_domi')->name('tiendas.pedidoDestroy');




Route::resource('/tiendas', 'TiendasController')->names('tiendas');
Route::resource('/zonas', 'ZonasController')->names('zonas');



/* Modulo de productos*/
Route::resource('/productos', 'ProductosController')->names('productos');
Route::get('/productos/keyup/{variable}', 'ProductosController@keyupproducto');


/* Modulo categorias de los productos*/
Route::get('/categoriasproductos/keyup/{variable}', 'CategoriasproductosController@keyup');
Route::resource('/categoriasproductos', 'CategoriasproductosController')->names('categoriasproductos');


/* Adicionales de los productos */
Route::get('adicionales/listar', 'AdicionalesController@index')->name('adicionales.index');
Route::get('adicionales/crear', 'AdicionalesController@crear')->name('adicionales.crear');
Route::PUT('adicionales/store', 'AdicionalesController@store')->name('adicionales.store');
Route::get('adicionales/show/{id}', 'AdicionalesController@show')->name('adicionales.show');
Route::get('adicionales/edicion/{id}', 'AdicionalesController@edicion')->name('adicionales.edicion');
Route::POST('adicionales/update/{id}', 'AdicionalesController@update')->name('adicionales.update');
Route::DELETE('adicionales/delete/{id}', 'AdicionalesController@delete')->name('adicionales.destroy');


/* Modulo de personas */
Route::resource('/personas', 'PersonasController')->names('personas');

Route::get('/perfil/{codigo}', 'PersonasController@perfil')->name('perfil.show');


/* Modulo de seugerencias */

Route::get('/sugerencias', 'FormulariosController@indexsugerencias')->name('sugerencias.index');
Route::get('/sugerencias/edit/{codigo]', 'FormulariosController@showSugerencia')->name('sugerencias.showsugerencia');
Route::DELETE('/sugerencias/delete/{codigo}', 'FormulariosController@deletesugerencias')->name('sugerencias.destroy');

Route::get('/contacto', 'FormulariosController@indexContacto')->name('contacto.index');


/* Modulo de notificaciones */

Route::get('/notification/get', 'HomeController@notification');
Route::get('/notification/show/{id?}', 'HomeController@ver_notification');


/* Modulo de planes */
Route::resource('/planes', 'PlanesController')->names('planes');
Route::get('/planes_asignar', 'PlanesController@asignar')->name('planes.asignar');
Route::post('/asignar_store', 'PlanesController@asignar_store')->name('planes.asignar_store');
Route::get('/asignaciones', 'PlanesController@asignaciones')->name('planes.asignaciones');

 	// ---  actualizar plan
	Route::post('/metodoUpdate', 'PlanesController@metodoPagoActualizacion')->name('planes.metodoUpdate');
	Route::post('/metodoUpdatePay/{valor}', 'PlanesController@metodoUpdatePay')->name('planes.metodoUpdatePay');
  Route::post('/metodoUpdatePayNequi/{valor}', 'PlanesController@metodoUpdatePayNequi')->name('planes.metodoUpdatePayNequi');

  //Ir al pago para actualizar plan
  Route::post('/pagoActualizacionPlan/{pago?}', 'PlanesController@pagoActualizacionPlan')->name('planes.pagoActualizacionPlan');

  /* Verificacion Pago con Nequi */
  Route::get('/wompi/verification/nequi/{id}', 'PlanesController@verification_nequi');
  Route::post('/wompi/verification/pagar/{id}', 'PlanesController@pagar_nequi');
  Route::get('/wompi/verification/transaction/{id}', 'PlanesController@verification_transaction');
  Route::post('/wompi/verification/registro_bd/{id}', 'PlanesController@registro_bd');
  Route::get('/cambio_plan', 'PlanesController@cambio_plan')->name('planes.cambio_plan');

  /*verificacion Pago con Nequi pero tarjetas de credito*/
  Route::get('/wompi/verification/nequi/tarjetas/{id}', 'PlanesController@verification_nequi');



/* Modulo de cupones */
Route::resource('/cupones', 'CuponesController')->names('cupones');


/* Modulo de Epayco */
Route::resource('/epayco', 'EpaycoController')->names('epayco');	
/* Modulo de Epayco */


/* Cerrar sesion*/
Route::get('/logout', 'HomeController@logout');

Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/Epayco.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Epayco extends Model
{
   
    protected $fillable = [
        'client_id', 
        'clave_id', 
        'public_key',
		'private_key',
        'epay_tienda', 
        'estado_epayco',
    ];
    
}

app/Http/Controllers/EpaycoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Epayco;
use Illuminate\Support\Facades\Crypt;
use Gate;
use DB;
use Auth;



class EpaycoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   

        Gate::authorize('haveaccess','epayco.index');

        $epaycos = Epayco::all();

        return view('epayco.index', compact('epaycos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        Gate::authorize('haveaccess','epayco.create');

        $tiendas = DB::table('tiendas')->get();
         $usuario = DB::table('role_user')
                        ->select('users.*', 'roles.*', 'role_user.*')
                        ->join('roles', 'role_user.role_id', '=', 'roles.id')
                        ->join('users', 'role_user.user_id', '=', 'users.id')
                        ->where('users.id', Auth::user()->id)->get();

        return view('epayco.create', compact('tiendas', 'usuario'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        
        Gate::authorize('haveaccess','epayco.create');
        
        $request->validate([
            'id_cliente' => 'required', 
            'id_clave' => 'required',
            'public_key' => 'required',
            'private_key' => 'required',
            'tienda' => 'required', 
            'estado_epayco' => 'required',
        ]);
        
        Epayco::create([
            'client_id'     => Crypt::encrypt($request->id_cliente),
            'clave_id'      => Crypt::encrypt($request->id_clave),
            'public_key'    => Crypt::encrypt($request->public_key),
            'private_key'   => Crypt::encrypt($request->private_key),
            'epay_tienda'   => $request->tienda,
            'estado_epayco' => $request->estado_epayco
        ]);
        
        return redirect()->route('epayco.index')
            ->with('status_success','Creado correctamente!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Epayco::where('id', '=', $id)->delete();

        return redirect()->route('epayco.index')
            ->with('status_success','Elimado correctamente!'); 

    }
}

resources/views/epayco/create.blade.php
@extends('layouts.app')

@section('content')


<div class="data-tables">
    <div class="main-content">
        <div class="container-fluid content-top-gap">
            <div class="data-tables">
                <div class="row">
                    <div class="col-lg-12 chart-grid mb-4">
                        <div class="card card_border p-4">
                            <div class="card-header chart-grid__header pl-0 pt-0">
                                Crear una nueva configuraci&oacute;n de Epayco
                            </div>
                        </div>
                        @include('custom.message')
                    </div>
                    
                    <div class="col-lg-12 chart-grid mb-4">
                        <div class="card card_border p-4">
                        {!! Form::open(['route' => 'epayco.store', 'files' => false]) !!}

                    @csrf
                    @method('POST')

                    <div class="form-group">
                        <label><b><code>(*) </code> ID CLIENTE:</b></label>
                        <input type="text" class="form-control" name="id_cliente" value="{{ old('id_cliente') }}" />
                    </div>

                    <div class="form-group">
                        <label><strong><code>(*) </code>ID CLAVE: </strong></label>
                        <input type="password" class="form-control" name="id_clave" value="{{ old('id_clave') }}">
                    </div>

                    <div class="form-group">
                        <label><strong><code>(*) </code>LLAVE PUBLICA: </strong></label>
                        <input type="password" class="form-control" name="public_key" value="{{ old('public_key') }}">
                    </div>

                    <div class="form-group">
                        <label><strong><code>(*) </code>LLAVE PRIVADA: </strong></label>
                        <input type="password" class="form-control" name="private_key" value="{{ old('private_key') }}">
                    </div>

                    @if($usuario[0]->slug == 'admin')
					<div class="form-group">
                        <label><strong><code>(*) </code>Tienda: </strong></label><br>
                            <select class="form-control mi-selector" name="tienda">
                                	<option value="aplicativo">Aplicativo</option>
                                @foreach($tiendas as $tienda)
                                	<option value="{{ $tienda->id_tienda }}">{{ $tienda->nombre_tienda }}</option>
                                @endforeach
                            </select>
                    </div>
                    @endif

                    <div class="form-group">
                        <label><strong><code>(*) </code>Estado: </strong></label><br>
                            <select class="form-control mi-selector" name="estado_epayco">
                                <option value="1">Activo</option>
                                <option value="2">Próximo</option>
                                <option value="0">Inactiva</option>
                            </select>
                    </div>

                    <center>
                        <a href="{{ route('cupones.index') }}" style="color:white; ">
                            <button type="button" class="btn btn-danger">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve" width="25px" height="25px" class=""><g><g>
                                            <g>
                                                <path d="M256,0C114.508,0,0,114.497,0,256c0,141.493,114.497,256,256,256c141.492,0,256-114.497,256-256    C512,114.507,397.503,0,256,0z M256,472c-119.384,0-216-96.607-216-216c0-119.385,96.607-216,216-216    c119.384,0,216,96.607,216,216C472,375.385,375.393,472,256,472z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
                                            </g>
                                        </g><g>
                                            <g>
                                                <path d="M343.586,315.302L284.284,256l59.302-59.302c7.81-7.81,7.811-20.473,0.001-28.284c-7.812-7.811-20.475-7.81-28.284,0    L256,227.716l-59.303-59.302c-7.809-7.811-20.474-7.811-28.284,0c-7.81,7.811-7.81,20.474,0.001,28.284L227.716,256    l-59.302,59.302c-7.811,7.811-7.812,20.474-0.001,28.284c7.813,7.812,20.476,7.809,28.284,0L256,284.284l59.303,59.302    c7.808,7.81,20.473,7.811,28.284,0C351.398,335.775,351.397,323.112,343.586,315.302z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
                                            </g>
                                        </g></g> </svg>
                                Cancelar registro
                            </button>
                        </a>

                        <button type="submit" class="btn btn-info" id="registroTienda">Crear Epayco</button>
                    </center>
                    {!! Form::close() !!}
                </div>
                    </div>
                    
                </div>
            </div>      
        </div>
    </div>
</div>

@endsection

resources/views/epayco/index.blade.php
<!-- Listado de las tiendas, no influye si es Administrador o Cliente -->

@extends('layouts.app')

@section('content')

<div class="data-tables">
    <div class="main-content">
        <div class="container-fluid content-top-gap">
            <div class="data-tables">
                <div class="row">
                    <div class="col-lg-12 chart-grid mb-4">
                        <div class="card card_border p-4">
                            <div class="card-header chart-grid__header pl-0 pt-0">
                                Configuraciones de Epayco en la Plataforma
                            </div>
                        </div>
                        @include('custom.message')
                    </div>
                    
                    <div class="col-lg-12 chart-grid mb-4">
                        <div class="card card_border p-4">
                            <!--<div class="messaging">
                                <b>Búsqueda de productos:</b>

                                <input type="text" name="buscadorProductos" id="buscadorProductos" class="form-control" placeholder="Busca tu producto..." />                            
                            </div>-->
                            <br>
                            <table class="table table-bordered table-hover" id="tabla-productos">
                                <thead>
                                    <tr>
                                        <th>ID Cliente</th>
                                        <th>ID Clave</th>
                                        <th>Tienda asignada</th>
                                        <th>Estado</th>
                                        <th colspan="3"><center>Acciones</center></th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($epaycos as $epayco)
                                    <tr>
                                        <td>{{ Crypt::decrypt($epayco->client_id) }}</td>
                                        <td>{{ Crypt::decrypt($epayco->clave_id) }}</td>
                                        <td>{{ $epayco->epay_tienda }}</td>
                                        @if($epayco->estado_epayco == '1')
                                        <td class="alert alert-success">Activo</td>
                                        @else
                                        <td class="alert alert-danger">Inactivo</td>                                
                                        @endif

                                        
                                        @if(Gate::authorize('haveaccess','epayco.destroy'))
                                        <td>
                                            <form method="POST" action="{{ route('epayco.destroy', $epayco->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/>
                                                    </svg>
                                                </button>
                                            </form>
                                        </td>
                                        @endif
                                    </tr>

                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                </div>
            </div>      
        </div>
    </div>
</div>

@include('custom.modales')

@endsection